---
abstract: 'Detect Zombie apocalypse'
author:
  - 'Glen Hinkle <tempire@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-ZombieApocalypse
requires:
  Mojolicious: 1.22
resources:
  repository: git://github.com/tempire/mojolicious-plugin-zombieapocalypse.git
version: 0.01
